Repository XENONnT/WFSim, pull requests merged in 2021-05, with the labels that each got.

#155 use database access to increase coverage of tests
  .github/scripts/create_readonly_utilix_config.sh
  .github/workflows/coveralls.yml
  .github/workflows/test_package.yml
  docs/pull_request_template.md
Labels: enhancement, testing

#152 Add tests
  .github/workflows/coveralls.yml
  tests/test_wfsim.py
Labels: enhancement, good first issue, testing

#161 Fixing SPE reconstruction bias due to truncation
  wfsim/core.py
  wfsim/strax_interface.py
Labels: bug
